/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ihc_interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class soport_help extends javax.swing.JFrame {

    /**
     * Creates new form Ayuda_soporte
     */
    public soport_help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Orders = new javax.swing.JLabel();
        Community = new javax.swing.JLabel();
        Borrowed = new javax.swing.JLabel();
        Catalog = new javax.swing.JLabel();
        Main_Page = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bar = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Search2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        Search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lupa.png"))); // NOI18N
        Search1.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1111, 789));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Book_open.png"))); // NOI18N
        jLabel1.setText("Book Hub");
        jLabel1.setIconTextGap(10);
        jLabel1.setRequestFocusEnabled(false);

        Orders.setText("Pedidos");
        Orders.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersMouseClicked(evt);
            }
        });

        Community.setText("Comunidad");
        Community.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Community.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommunityMouseClicked(evt);
            }
        });

        Borrowed.setText("Mis Préstamos");
        Borrowed.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Borrowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BorrowedMouseClicked(evt);
            }
        });

        Catalog.setText("Catálogo");
        Catalog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Catalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatalogMouseClicked(evt);
            }
        });

        Main_Page.setText("Página Principal");
        Main_Page.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Main_Page.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Main_PageMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(107, 127, 152));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/looking.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, 170, 170));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Ayuda y soporte para el usuario");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        bar.setBackground(new java.awt.Color(107, 127, 165));
        bar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        bar.setText("  Ingresar consulta o problema");
        bar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barActionPerformed(evt);
            }
        });
        jPanel2.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 720, 30));

        Search.setBackground(new java.awt.Color(0, 0, 0));
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setText("Buscar");
        Search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel2.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 72, 30));

        Search2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lupa.png"))); // NOI18N
        Search2.setToolTipText("");
        jPanel2.add(Search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 93, 30, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setText("Preguntas frecuentes");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel6.setText("¿Cual es el plazo maximo de entrega de un libro?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel7.setText("¿Hay algun limite de libros para solicitar prestamo? ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel8.setText("Ver más preguntas frecuentes");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setWheelScrollingEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(107, 127, 152));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Sí, existe un límite en la cantidad de libros que puedes solicitar en préstamo, \ndependiendo de tu categoría dentro de la universidad:\nEstudiantes de pregrado: Hasta 3 libros en préstamo simultáneo.\nEstudiantes de posgrado: Hasta 5 libros en préstamo simultáneo.\nDocentes e investigadores: Hasta 7 libros en préstamo simultáneo.\nEste límite busca asegurar que los recursos estén disponibles para todos los usuarios de la biblioteca. Si necesitas más libros para un proyecto o investigación \nespecífica, puedes solicitar una autorización especial. Estas solicitudes son evaluadas caso por  caso y estarán sujetas a la disponibilidad de los materiales.\nRecuerda que todos los préstamos están sujetos a los plazos establecidos por la biblioteca y al cumplimiento de las políticas de renovación y devolución. \nEl incumplimiento de estas normas puede afectar tu capacidad de realizar nuevos préstamos en el futuro.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 880, 170));

        jTextArea2.setBackground(new java.awt.Color(107, 127, 152));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("El plazo máximo de entrega de un libro en nuestra plataforma es de 15 días calendario a partir de la fecha en que se realiza el préstamo. \nEste plazo está diseñado para garantizar que todos los estudiantes y personal universitario tengan acceso equitativo a los recursos disponibles.\nSi necesitas más tiempo, puedes realizar una solicitud de renovación antes de la fecha de vencimiento, siempre y cuando el libro no tenga reservas \npendientes por parte de otros usuarios. Las renovaciones pueden otorgar hasta 15 días adicionales, dependiendo de la disponibilidad del material.\nRecuerda que el retraso en la devolución genera una penalidad de S/0.50 por día de retraso por libro. Las multas acumuladas deberán ser pagadas\nantes de realizar nuevos préstamos.Para evitar inconvenientes, te recomendamos que marques en tu calendario la fecha límite o habilites las\nnotificaciones en nuestra plataforma para recibir recordatorios. Si tienes dudas sobre el plazo de entrega o cómo realizar renovaciones, no dudes en\n contactarnos a través de nuestros canales de soporte.");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(null);
        jTextArea2.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 940, 160));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Main_Page)
                .addGap(31, 31, 31)
                .addComponent(Orders)
                .addGap(18, 18, 18)
                .addComponent(Community)
                .addGap(18, 18, 18)
                .addComponent(Borrowed)
                .addGap(18, 18, 18)
                .addComponent(Catalog)
                .addGap(50, 50, 50))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Orders)
                    .addComponent(Community)
                    .addComponent(Borrowed)
                    .addComponent(Catalog)
                    .addComponent(Main_Page))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersMouseClicked
        Reservations res = new Reservations();
        res.setLocationRelativeTo(null);
        res.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrdersMouseClicked

    private void CommunityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommunityMouseClicked
        Community com = new Community();
        com.setLocationRelativeTo(null);
        com.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CommunityMouseClicked

    private void BorrowedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BorrowedMouseClicked
        Borrowed_Books bo = new Borrowed_Books();
        bo.setLocationRelativeTo(null);
        bo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BorrowedMouseClicked

    private void CatalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatalogMouseClicked
        Search_Books se = new Search_Books();
        se.setLocationRelativeTo(null);
        se.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CatalogMouseClicked

    private void Main_PageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Main_PageMouseClicked
        Main_Page main = new Main_Page();
        main.setLocationRelativeTo(null);
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Main_PageMouseClicked

    private void barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        String query = bar.getText().toLowerCase();

        if (query.contains("4ta")) {
            System.out.println("Se detectó '4ta' en la búsqueda"); // Mensaje de depuración
            Book_4ta_Edicion result4ta = new Book_4ta_Edicion(); // Ventana que muestra el libro de la 4ta edición
            result4ta.setLocationRelativeTo(null);
            result4ta.setVisible(true);
            this.dispose();
        } else if (query.contains("2da")) {
            System.out.println("Se detectó '2da' en la búsqueda"); // Mensaje de depuración
            Book_2da_Edicion result2da = new Book_2da_Edicion(); // Ventana que muestra el libro de la 2da edición
            result2da.setLocationRelativeTo(null);
            result2da.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados para: " + query);
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Borrowed;
    private javax.swing.JLabel Catalog;
    private javax.swing.JLabel Community;
    private javax.swing.JLabel Main_Page;
    private javax.swing.JLabel Orders;
    private javax.swing.JButton Search;
    private javax.swing.JLabel Search1;
    private javax.swing.JLabel Search2;
    private javax.swing.JTextField bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
